/// Flutter icons KnctUIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KnctUIcon
///      fonts:
///       - asset: fonts/KnctUIcon.ttf
///
/// 
///

import 'package:flutter/widgets.dart';

class KnctUIcon {
  KnctUIcon._();

  static const _kFontFam = 'KnctUIcon';

  static const IconData answers = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData education = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData questions = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData trending_2 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData email_3 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData home_3 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData add_question = const IconData(0xe809, fontFamily: _kFontFam);
}
