/// Flutter icons U
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  U
///      fonts:
///       - asset: fonts/U.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class U {
  U._();

  static const _kFontFam = 'U';

  static const IconData u_outline = const IconData(0xe800, fontFamily: _kFontFam);
}
