/// Flutter icons KnctU
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KnctU
///      fonts:
///       - asset: fonts/KnctU.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class KnctU {
  KnctU._();

  static const _kFontFam = 'KnctU';

  static const IconData wifi_tethering = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData chat_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData school = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData email_1 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData questions = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData answers = const IconData(0xe80d, fontFamily: _kFontFam);
}
